/** Default catalog — seeded into Firestore once (admin can edit after) */

export const DEFAULT_CATEGORIES = [
  { id: 'vegetables', labelEn: 'Vegetables / Curry', labelGu: 'શાક', order: 1 },
  { id: 'carbs', labelEn: 'Carbohydrates', labelGu: 'કારબોદિત', order: 2 },
  { id: 'dalRice', labelEn: 'Side Dishes', labelGu: 'સહાયક વાનગીઓ', order: 3 },
  { id: 'special', labelEn: 'Special Items', labelGu: 'સ્પેશિયલ', order: 4 },
]

export const DEFAULT_ITEMS = [
  // શાક — yes / no
  { id: 'kobi-bateka-tameta', categoryId: 'vegetables', en: 'Kobi Bateka Tameta', gu: 'કોબી બટેકા ટમેટા', voteType: 'yes_no' },
  { id: 'kobi-nu-shaak', categoryId: 'vegetables', en: 'Kobi nu Shaak', gu: 'કોબીનું શાક', voteType: 'yes_no' },
  { id: 'bhindo', categoryId: 'vegetables', en: 'Bhindo', gu: 'ભીંડો', voteType: 'yes_no' },
  { id: 'bateka-ni-suki-bhaji', categoryId: 'vegetables', en: 'Bateka ni Suki Bhaji', gu: 'બટેકાની સુકિભાજી', voteType: 'yes_no' },
  { id: 'bateka-nu-rasawalu', categoryId: 'vegetables', en: 'Bateka nu Rasawalu', gu: 'બટેકાનુ રસાવાળુ', voteType: 'yes_no' },
  { id: 'akha-ringana-nu-shaak', categoryId: 'vegetables', en: 'Akha Ringana nu Shaak', gu: 'આખા રીંગણાનું શાક', voteType: 'yes_no' },
  { id: 'ringana-bateka-nu-shaak', categoryId: 'vegetables', en: 'Ringana Bateka nu Shaak', gu: 'રીંગણા બટેકાનું શાક', voteType: 'yes_no' },
  { id: 'bateka-chips', categoryId: 'vegetables', en: 'Bateka Chips', gu: 'બટેકા ચીપ્સ', voteType: 'yes_no' },
  { id: 'vatana-bateka', categoryId: 'vegetables', en: 'Vatana Bateka', gu: 'વટાણા બટેકા', voteType: 'yes_no' },
  { id: 'dudhi-dal', categoryId: 'vegetables', en: 'Dudhi Dal', gu: 'દુધી દાળ', voteType: 'yes_no' },
  { id: 'galka', categoryId: 'vegetables', en: 'Galka', gu: 'ગલકા', voteType: 'yes_no' },
  { id: 'fulavar-bateka-nu-shaak', categoryId: 'vegetables', en: 'Fulavar Bateka nu Shaak', gu: 'ફુલાવર બટેકાનું શાક', voteType: 'yes_no' },
  { id: 'gatte', categoryId: 'vegetables', en: 'Gatte', gu: 'ગટ્ટે', voteType: 'yes_no' },
  { id: 'ganthiya', categoryId: 'vegetables', en: 'Ganthiya', gu: 'ગાંઠિયા', voteType: 'yes_no' },
  { id: 'dahi-ni-tikhari', categoryId: 'vegetables', en: 'Dahi ni Tikhari', gu: 'દહિની તિખારી', voteType: 'yes_no' },
  { id: 'chole', categoryId: 'vegetables', en: 'Chole', gu: 'છોલે', voteType: 'yes_no' },
  { id: 'adad-ni-dal', categoryId: 'vegetables', en: 'Adad ni Dal', gu: 'અડદની દાળ', voteType: 'yes_no' },
  { id: 'mix-dal', categoryId: 'vegetables', en: 'Mix Dal', gu: 'મિક્ષ દાળ', voteType: 'yes_no' },
  { id: 'totha', categoryId: 'vegetables', en: 'Totha', gu: 'ટોઠા', voteType: 'yes_no' },
  { id: 'mag-nu-koru', categoryId: 'vegetables', en: 'Mag nu Koru', gu: 'મગનું કોરું', voteType: 'yes_no' },
  { id: 'mag-nu-rasawalu', categoryId: 'vegetables', en: 'Mag nu Rasawalu', gu: 'મગનુ રસાવાળુ', voteType: 'yes_no' },
  { id: 'mag-ni-dal-nu-shaak', categoryId: 'vegetables', en: 'Mag ni Dal nu Shaak', gu: 'મગની દાળનું શાક', voteType: 'yes_no' },
  { id: 'chola', categoryId: 'vegetables', en: 'Chola', gu: 'ચોળા', voteType: 'yes_no' },
  { id: 'vaal', categoryId: 'vegetables', en: 'Vaal', gu: 'વાલ', voteType: 'yes_no' },
  { id: 'chana', categoryId: 'vegetables', en: 'Chana', gu: 'ચણા', voteType: 'yes_no' },
  { id: 'chana-bateka', categoryId: 'vegetables', en: 'Chana Bateka', gu: 'ચણા બટેકા', voteType: 'yes_no' },
  { id: 'paneer-nu-shaak', categoryId: 'vegetables', en: 'Paneer nu Shaak', gu: 'પનીરનું શાક', voteType: 'yes_no' },
  { id: 'cheese-corn-tomato', categoryId: 'vegetables', en: 'Cheese Corn Tomato', gu: 'ચીઝ કોર્ન ટોમેટો', voteType: 'yes_no' },
  { id: 'sev-tameta', categoryId: 'vegetables', en: 'Sev Tameta', gu: 'સેવ ટામેટાં', voteType: 'yes_no' },
  { id: 'karela-nu-shaak', categoryId: 'vegetables', en: 'Karela nu Shaak', gu: 'કારેલાનું શાક', voteType: 'yes_no' },
  { id: 'tindora-bateka', categoryId: 'vegetables', en: 'Tindora Bateka', gu: 'ટીંડોરા બટેકા', voteType: 'yes_no' },
  { id: 'ringana-nu-bhadthu', categoryId: 'vegetables', en: 'Ringana nu Bhadthu', gu: 'રીંગણાનુ ભડથુ', voteType: 'yes_no' },
  { id: 'palak-nu-shaak', categoryId: 'vegetables', en: 'Palak nu Shaak', gu: 'પાલકનું શાક', voteType: 'yes_no' },
  { id: 'math-nu-shaak', categoryId: 'vegetables', en: 'Math nu Shaak', gu: 'મઠ નું શાક', voteType: 'yes_no' },

  // કારબોદિત — number
  { id: 'rotli', categoryId: 'carbs', en: 'Rotli', gu: 'રોટલી', voteType: 'integer' },
  { id: 'farali-rotli', categoryId: 'carbs', en: 'Farali Rotli', gu: 'ફરાળી રોટલી', voteType: 'integer' },
  { id: 'bhakhri', categoryId: 'carbs', en: 'Bhakhri', gu: 'ભાખરી', voteType: 'integer' },
  { id: 'dudhi-thepla', categoryId: 'carbs', en: 'Dudhi Thepla', gu: 'દુધી થેપલા', voteType: 'integer' },
  { id: 'aalu-parotha', categoryId: 'carbs', en: 'Aalu Parotha', gu: 'આલુ પરોઠા', voteType: 'integer' },
  { id: 'parotha', categoryId: 'carbs', en: 'Parotha', gu: 'પરોઠા', voteType: 'integer' },
  { id: 'biscuit-bhakhri-l', categoryId: 'carbs', en: 'Biscuit Bhakhri (L)', gu: 'બિસ્કિટ ભાખરી (L)', voteType: 'integer' },
  { id: 'biscuit-bhakhri-m', categoryId: 'carbs', en: 'Biscuit Bhakhri (M)', gu: 'બિસ્કિટ ભાખરી (M)', voteType: 'integer' },
  { id: 'biscuit-bhakhri-s', categoryId: 'carbs', en: 'Biscuit Bhakhri (S)', gu: 'બિસ્કિટ ભાખરી (S)', voteType: 'integer' },

  // સહાયક વાનગીઓ — yes / no
  { id: 'dal', categoryId: 'dalRice', en: 'Dal', gu: 'દાળ', voteType: 'yes_no' },
  { id: 'bhaat', categoryId: 'dalRice', en: 'Bhaat', gu: 'ભાત', voteType: 'yes_no' },
  { id: 'kadhi', categoryId: 'dalRice', en: 'Kadhi', gu: 'કઢી', voteType: 'yes_no' },
  { id: 'khichdi', categoryId: 'dalRice', en: 'Khichdi', gu: 'ખીચડી', voteType: 'yes_no' },
  { id: 'dal-fry', categoryId: 'dalRice', en: 'Dal Fry', gu: 'દાળ ફ્રાય', voteType: 'yes_no' },
  { id: 'pulao', categoryId: 'dalRice', en: 'Pulao', gu: 'પુલાવ', voteType: 'yes_no' },
  { id: 'jeera-rice', categoryId: 'dalRice', en: 'Jeera Rice', gu: 'જીરા રાઈસ', voteType: 'yes_no' },
  { id: 'sabudana-khichdi', categoryId: 'dalRice', en: 'Sabudana Khichdi', gu: 'સાબુદાણા ખીચડી', voteType: 'yes_no' },
  { id: 'moraiya-ni-khichdi', categoryId: 'dalRice', en: 'Moraiya ni Khichdi', gu: 'મોરૈયા ની ખીચડી', voteType: 'yes_no' },
  { id: 'vaghareli-khichdi', categoryId: 'dalRice', en: 'Vaghareli Khichdi', gu: 'વઘારેલી ખીચડી', voteType: 'yes_no' },
  { id: 'chinese-fried-rice', categoryId: 'dalRice', en: 'Chinese Fried Rice', gu: 'ચાઈનીઝ ફ્રાઈડ રાઈસ', voteType: 'yes_no' },
  { id: 'schezwan-fried-rice', categoryId: 'dalRice', en: 'Schezwan Fried Rice', gu: 'સેઝવાન ફ્રાઈડ રાઈસ', voteType: 'yes_no' },

  // સ્પેશિયલ — yes / no
  { id: 'panipuri', categoryId: 'special', en: 'Panipuri', gu: 'પાણીપુરી', voteType: 'yes_no' },
  { id: 'manchurian', categoryId: 'special', en: 'Manchurian', gu: 'મન્ચુરિયન', voteType: 'yes_no' },
  { id: 'kheer', categoryId: 'special', en: 'Kheer', gu: 'ખીર', voteType: 'yes_no' },
  { id: 'dudh-paua', categoryId: 'special', en: 'Dudh Paua', gu: 'દૂધ પૌઆ', voteType: 'yes_no' },

  // સ્પેશિયલ — number
  { id: 'ragda-petis', categoryId: 'special', en: 'Ragda Petis', gu: 'રગડા પેટીસ', voteType: 'integer' },
  { id: 'dal-bati', categoryId: 'special', en: 'Dal Bati (1=1/4)', gu: 'દાળ બાટી (1=1/4)', voteType: 'integer' },
  { id: 'sabudana-na-vada', categoryId: 'special', en: 'Sabudana na Vada', gu: 'સાબુદાણાના વડા', voteType: 'integer' },
  { id: 'frankie', categoryId: 'special', en: 'Frankie', gu: 'ફ્રેન્કી', voteType: 'integer' },
  { id: 'samosa', categoryId: 'special', en: 'Samosa', gu: 'સમોસા', voteType: 'integer' },
  { id: 'bhaji-na-pav', categoryId: 'special', en: 'Bhaji na Pav', gu: 'ભાજીના પાવ', voteType: 'integer' },
]
